exports.japost = ( pushname ) => {
return `Hallo Kak *${pushname}*

*FORMAT JAPOST EMERALD STORE*

▪️AKUN : _FF/ML/PUBG/DLL?_
▪️SPEK AKUN :
▪️LOG : 
▪️EPAS BERAPA × : 
▪️HARGA :

♨️JIKA MINAT HUBUNGI WHATSAPP SAYA (EMERALD STORE)
♨️GUNAKAN JASA REKBER EMERALD STORE AGAR TERINDAR DARI PENIPUAN💦`
}